%color r m g c b w y k
clear all;
clc;
dt = .02;
leftrange = pi;
rightrange = pi;
x=[-leftrange:.2:rightrange];
y = ones(size(x));
Z1=x+y*i;
Z2=x+y*i*2;
Z3=y+x*i;
Z4=y*pi/2+x*i;
hold;
plot(real(Z1), imag(Z1), '-g');
plot(real(Z2), imag(Z2), '-b');
plot(real(Z3), imag(Z3), '-y');
plot(real(Z4), imag(Z4), '-k');
axis equal;
figure;
Z1=cos(Z1);
Z2=cos(Z2);
Z3=cos(Z3);
Z4=cos(Z4);
hold;
plot(real(Z1), imag(Z1), '-g');
plot(real(Z2), imag(Z2), '-b');
plot(real(Z3), imag(Z3), '-y');
plot(real(Z4), imag(Z4), '-k');
axis equal;
